# Generated by Django 4.1.4 on 2023-01-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_user_profileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
